name: sass_watcher
version: 0.0.1
description: Quick, fragile, transient hack to compile sass without pub transformer.

environment:
  sdk: '>=1.24.0 <2.0.0'

dependencies:
  watcher:
  args:
  glob:
  tuple: ^1.0.0
  sass: ^1.0.0-beta.2
dev_dependencies:
  test: '>=0.12.0 <0.13.0'
